### ISSUE TITLE
ES Modules may not assign module.exports or exports.*, Use ESM export syntax, instead

### ISSUE THREAD

**Issue by emqMalte** [passageidentity/passage-node#100]
Within a '[next@14.0.4](https://github.com/vercel/next.js/releases/tag/v14.0.4)' app I am no longer able to use `@passageidentity/passage-node@2.6.0` with the following error:

> Unhandled Runtime Error
Error: ES Modules may not assign module.exports or exports.*, Use ESM export syntax, instead: (rsc)/./node_modules/.pnpm/@passageidentity+passage-node@2.6.0_encoding@0.1.13/node_modules/@passageidentity/passage-node/lib/esm/index.js

This seems to be caused by the presence of both module.exports and export default in https://github.com/passageidentity/passage-node/blob/e9bf6ca5dcf77922ecbe18102590ef263a6e68e2/src/index.ts#L26-L28
which are then also both included in the `lib/cjs/index.js` and `lib/esm/index.js` outputs

**Comment by ctran88** [comment]
This issue should be fixed now in version [2.10.1](https://www.npmjs.com/package/@passageidentity/passage-node/v/2.10.1)
