### ISSUE TITLE
Feature Request: Plumb fetchApi through to PassageConfig

### ISSUE THREAD

**Issue by dusty-phillips** [passageidentity/passage-node#129]
I noticed that the generated code can have a fetch API dropped in place of `fetch`, here:

https://github.com/passageidentity/passage-node/blob/main/src/utils/apiConfiguration.ts#L13

However, the configuration in all Passage calls is hard-coding this configuration to use the default `node-fetch` implementation. It would be nice if I could set a different fetcher on the PassageConfig and have it plumbed through to any calls that need to make requests.

For my use case (experiments with the bun runtime), this would make mocking and telemetry much simpler.

**Comment by ctran88** [comment]
Sorry for the long delay! This was added in [v2.11.2](https://github.com/passageidentity/passage-node/blob/main/CHANGELOG.md#2112)
