### ISSUE TITLE
Bad types

### ISSUE THREAD

**Issue by joshua-richardson-88** [passageidentity/passage-node#40]
In /src/classes/passage.ts line 48 should be changed from `async authenticateRequest(req: Request): Promise<string | false> {` to `async authenticateRequest(req: Request): Promise<string> {` as there is no part of the internal functions that returns false. 

I think the offending line actually comes from line 149 `async authenticateRequestWithCookie(req: Request): Promise<string | false> {`. 
This should also have the `| false` removed as well. Not sure how typescript was allowing this through build.

**Comment by macleanevans** [comment]
Hi @joshua-richardson-88, thanks for reporting this issue. This has been fixed in the linked PR above and is published in `v2.0.2`. I am going to close this issue, but feel free to reopen it if you believe the issue persists.
