### ISSUE TITLE
Export User types

### ISSUE THREAD

**Issue by jwnx** [passageidentity/passage-node#51]
User types are defined locally, but not exported: https://github.com/passageidentity/passage-node/blob/4a2321f13309f2977d1dd237bf819941b683b432/src/classes/User.ts

It is useful to know what kind of data you are receiving back when performing user operations. Currently, we are duplicating them in our code.

Cheers,

**Comment by jenn-macfarlane** [comment]
Hi there @jwnx ! Thanks for the suggestion. We've just deployed the newest version of the SDK to include exports for User types (as well as a couple other types that may be useful). You should now be able to import the types you need!
