### ISSUE TITLE
Add local-only JWT validation

### ISSUE THREAD

**Issue by pistachiomatt** [passageidentity/passage-node#68]
Running `validAuthToken` takes 100–200ms per request. For API requests this is unnoticable, but for HTML requests, this adds a delay. With your competitors, I solved this by checking the JWT locally first which would avoid any network delays for about 80% of the time. Add a helper function that does this.

**Comment by flanagankp** [comment]
Closing this issue. For future posterity, the JWT validation functions cache the JWKS signing key so as long as the same `Passage` object instance is used only the first request will make a network call and subsequent requests will occur locally.
